AWSTemplateFormatVersion: "2010-09-09"

Parameters:
  InstanceType:
    Description: EC2 Instance type
    Type: String
    Default: t2.micro
    AllowedValues:
      - t2.micro
      - t2.small

Resources:
  EC2Instance:
    Type: 'AWS::EC2::Instance'
    Properties: 
      InstanceType: t2.micro
      ImageId: ami-01cc34ab2709337aa
      SecurityGroups:
        - !Ref InstanceSecurityGroup

  InstanceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: EC2 Security Group
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0

Outputs:
  InstanceId:
    Description: InstanceId of EC2
    Value: !Ref EC2Instance
  PublicDNS:
    Description: Public DNS of EC2
    Value: !GetAtt
            - EC2Instance
            - PublicDnsName
  PublicIP:
    Description: Public IP Address of EC2
    Value: !GetAtt
            - EC2Instance
            - PublicIp
